// <auto-generated />
using System;
using GoogleKeepDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoogleKeepDB.Migrations
{
    [DbContext(typeof(KeepContext))]
    [Migration("20180802123046_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoogleKeepDB.Model.Checklist", b =>
                {
                    b.Property<int>("checklistID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("item");

                    b.Property<int?>("keepID");

                    b.HasKey("checklistID");

                    b.HasIndex("keepID");

                    b.ToTable("Checklist");
                });

            modelBuilder.Entity("GoogleKeepDB.Model.Keep", b =>
                {
                    b.Property<int>("keepID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("isPinned");

                    b.Property<string>("label");

                    b.Property<string>("plainText");

                    b.Property<string>("title")
                        .IsRequired();

                    b.HasKey("keepID");

                    b.ToTable("Keep");
                });

            modelBuilder.Entity("GoogleKeepDB.Model.Checklist", b =>
                {
                    b.HasOne("GoogleKeepDB.Model.Keep")
                        .WithMany("checklist")
                        .HasForeignKey("keepID");
                });
#pragma warning restore 612, 618
        }
    }
}
